/** @description : clés utilisées par le StorageService */
export enum SESSION_CLES {
    COMPTE_UTILISATEUR_CONNECTE = 'COMPTE_UTILISATEUR_CONNECTE',
    RECHERCHE_DEMANDE_FILTRES = 'RECHERCHE_DEMANDE_FILTRES',
    RECUP_DEMANDE_TELERC = 'RECUP_DEMANDE_TELERC',
    NOUVELLE_DEMANDE_INFOS_PRINCIPALES = 'NOUVELLE_DEMANDE_INFOS_PRINCIPALES',
    DEMANDE_DUPLICATION = 'DEMANDE_DUPLICATION',
}
